container:
  type: ColumnPanel
  properties: {col_widths: '{}'}
components:
- type: ColumnPanel
  properties: {role: card, tooltip: '', border: '', foreground: '', visible: true,
    wrap_on: mobile, col_spacing: medium, spacing_above: small, col_widths: '{}',
    spacing_below: small, background: ''}
  name: card_1
  layout_properties: {grid_position: 'RVLNXM,ZXNEYG', full_width_row: true}
  components:
  - type: Label
    properties: {role: headline, align: left, tooltip: '', border: '', foreground: '',
      visible: true, text: '  Config', font_size: null, font: '', spacing_above: small,
      icon_align: left, spacing_below: small, italic: false, background: '', bold: false,
      underline: false, icon: ''}
    name: label_1
    layout_properties: {grid_position: 'HEMRFW,LFFFYQ', full_width_row: true}
  - type: Button
    properties: {role: secondary-color, align: center, tooltip: '', border: '', enabled: true,
      foreground: '', visible: true, text: Delete data, font_size: null, font: '',
      spacing_above: small, icon_align: left, spacing_below: small, italic: false,
      background: '', bold: false, underline: false, icon: 'fa:database'}
    name: all_delete_button
    layout_properties: {grid_position: 'XGPNSY,KFHYRB'}
    event_bindings: {click: all_delete_button_click}
is_package: true
